### ISSUE TITLE
Session->GetAttribute in Layout\Info.php Error

### ISSUE THREAD

**Issue by pauluz** [jaws-project/jaws#189]
Very fast and clean install Jaws 1.2.0 (clone from github)
During the instalation on step Database there is:
( ! ) Fatal error: Call to a member function GetAttribute() on null in \jaws-git\gadgets\Layout\Info.php on line 80
I have database created - database user is correct and 
I choose Is DB Admin to true and test both sql driver.
Error is on Session property 
generally: I can't install Jaws :(

**Comment by afz** [comment]
Thanks for report, this error already fixed.
